version: '3'

services:
  app:
    build: .
    container_name: bot_ia
    command: ./.docker/start-app.sh
    volumes:
      - .:/home/python/app
    networks:
        - bot

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${MYSQL_PASSWORD}'
    ports:
      - '9090:3306'
    networks:
        - bot

networks:
    bot:
        driver: bridge
